### ISSUE TITLE
suggestions to change the port used

### ISSUE THREAD

**Issue by raykai** [Uuvana-Studios/longvinter-windows-server#2] opened 2022-02-25 02:55 UTC
Hi, the port number 7777 is already used by default for the game Conan Exile dedicated server. 
Can you consider changing the port number used or adding a way for us to change the port the server uses for Longvinter? 

Thanks.

**Comment by sirNugg3ts** [comment] 2022-02-25 02:57
At the moment this port is being used due to UE4 default values.
This will be fixed in an update soon but it is not top priority.

**Comment by raykai** [comment] 2022-02-25 04:06
if its UE4 can't we just do add  -log -port=(the port number we want to use eg: -port=9999) to the right side of the path in the shortcut?

**Comment by Jalsson** [comment] 2022-02-25 10:29
> > At the moment this port is being used due to UE4 default values. This will be fixed in an update soon but it is not top priority.
> 
> If it's UE4 can't we just do -log -port=(the port number we want to use eg: -port=9999) to the right side of the path in the shortcut?

You are free to try this. Please report back if it works!

**Comment by Redeye123** [comment] 2022-03-03 11:33
-log -Port=Number -QueryPort=Number 
 
 Works as intended (Longtime Ark server hoster) Tried myself 
![afbeelding](https://user-images.githubusercontent.com/828563/156556813-b32e67b5-be6f-44a0-960d-26565bac322d.png)

**Closed** 2022-04-22 16:27 UTC
Labels: enhancement
